global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "http-example"

    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        port: 8080

    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_job]
        action: keep
        regex: web
      - source_labels: [__meta_docker_container_name]
        action: replace
        target_label: container_name
        regex: ^/(.+)$
        replacement: "$1"

  - job_name: "docker-host"
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
